let quotes = [
  "money is not a thing",
  "Getting rich is about knowing what to do, who to do it with, and when to do it.",
  "If you don’t know yet what you should work on, the most important thing is to figure it out. You should not grind at a lot of hard work until you figure out what you should be working on.",
  "figuring out the point of maximum leverage to actually create wealth and capture some of that created wealth.",
  "Seek wealth, not money or status. Wealth is having assets that earn while you sleep.",
  "You’re not going to get rich renting out your time. You must own equity—a piece of a business—to gain your financial freedom.",
  "You will get rich by giving society what it wants but does not yet know how to get. At scale.",
  "Play iterated games. All the returns in life, whether in wealth, relationships, or knowledge, come from compound interest.",
  "Learn to sell. Learn to build. If you can do both, you will be unstoppable.",
  "Fortunes require leverage. Business leverage comes from capital, people, and products with no marginal cost of replication (code and media).",
  "Code and media are permissionless leverage. They’re the leverage behind the newly rich.",
  "If you can’t code, write books and blogs, record videos and podcasts.",
  "Study microeconomics, game theory, psychology, persuasion, ethics, mathematics, and computers.",
  "Is this authentic to me? Is it myself that I am projecting?.",
  "Reading is faster than listening. Doing is faster than watching.",

  "I’m not saying it takes decades to execute, but the better part of a decade may be figuring out what you can uniquely provide.",
  "thousand. With a leveraged worker, judgment is far more important than how much time they put in or how hard they work.",
  "Retirement is when you stop sacrificing today for an imaginary tomorrow. When today is complete, in and of itself, you’re retired.",
  "Lusting for money is bad for us because it is a bottomless pit. It will always occupy your mind. If you love money, and you make it, there’s never enough.",
  "I think the best way to stay away from this constant love of money is to not upgrade your lifestyle as you make money.",
  "I value freedom above everything else.",
  "To the extent money buys freedom, it’s great. But to the extent it makes me less free, which it definitely does at some level as well, I don’t like it.",
  "build your character in a certain way, then your character becomes your destiny.",
  "If you are a trusted, reliable, high-integrity, long-term-thinking dealmaker, when other people want to do deals but don’t know how to do them in a trustworthy manner with strangers, they will literally approach you and give you a cut of the deal just because of the integrity and reputation you’ve built up.",
  "Nivi said, “In a long-term game, it seems that everybody is making each other rich. And in a short-term game, it seems like everybody is making themselves rich.”",
  "Trying to build business.",
  "relationships well in advance of doing business is a complete waste of time.",
  "Be a maker who makes something interesting people want. Show your craft, practice your craft, and the right people will eventually find you.",
  "The worst outcome in this world is not having self-esteem. If you don’t love yourself, who will?.",
  "I think you just have to be very careful about doing things you are fundamentally not going to be proud of, because they will damage you.",
  "BE PATIENT .",
  "Apply specific knowledge with leverage and eventually, you will get what you deserve.",
  "It takes time—even once you have all of these pieces in place, there is an indeterminate amount of time you have to put in. If you’re counting, you’ll run out of patience before success actually arrives.",
  "Most of history was built by young people.",
  "older. The only way to truly learn something is by doing it. Yes, listen to guidance. But don’t wait.",
  "Always pay it forward. And don’t keep count.",
  "You have to do hard things anyway to create.",
  "Most of the time, the person you have to become to make money is a high-anxiety, high-stress, hard-working, competitive person.",
  "if you want to get rich over your life in a deterministically predictable way, stay on the bleeding edge of trends and study technology, design, and art—become really good at something.",
  "Picking the direction you’re heading in for every decision is far, far more important than how much force you apply.",
  "What you feel tells you nothing about the facts—it merely tells you something about your estimate of the facts.",
  "I also encourage taking at least one day a week (preferably two, because if you budget two, you’ll end up with one) where you just have time to think.",
  "You absolutely need habits to function.",
  "If all your beliefs line up into neat little bundles, you should be highly suspicious.",
  "With modern technology and large workforces and capital, our decisions are leveraged more and more.",
  "The best mental models I have found came through evolution, game theory, and Charlie Munger.",
  "Those are extremely important. Crack open a basic math book, and make sure you are really good at multiplying, dividing, compounding, probability, and statistics.",
  "BLACK SWANS There’s a new branch of probability statistics, which is really around tail events.",
  "Simple heuristic: If you’re evenly split on a difficult decision, take the path more painful in the short term.",
  "As you know, most of the gains in life come from suffering in the short term so you can get paid in the long term.",
  "So you generally want to lean into things with short-term pain, but long-term gain.",
  "What are the most efficient ways to build new mental models? Read a lot—just read.",
  "Reading science, math, and philosophy one hour per day will likely put you at the upper echelon of human success within seven years.",
  "Learn how to learn and read the books.",
  "A calm mind, a fit body, and a house full of love.",
  "Happiness to me is mainly not suffering, not desiring, not thinking too much about the future or the past, really embracing the present moment and the reality of what is, and the way it is.",
  "Nature has no concept of happiness or unhappiness. Nature follows unbroken mathematical laws and a chain of cause and effect from the Big Bang to now. Everything is perfect exactly the way it is. It is only in our particular minds we are unhappy or not happy, and things are perfect or imperfect because of what we desire.",
  "However, if you view yourself as a bacteria or an amoeba—or if you view all of your works as writing on water or building castles in the sand, then you have no expectation for how life should “actually” be.",
  "Happiness is what’s there when you remove the sense that something is missing in your life.",
  "We think of ourselves as fixed and the world as malleable, but it’s really we who are malleable and the world is largely fixed.",
  "Happiness, love, and passion…aren’t things you find—they’re choices you make.",
  "Memory and identity are burdens from the past preventing us from living freely in the present.",
  "“Enlightenment is the space between your thoughts.”",
  "It’s always the next thing, then the next thing, the next thing after that, then the next thing after that creating this pervasive anxiety.",
  "I think it’s important just being aware the anxiety is making you unhappy. The anxiety is just a series of running thoughts.",
  "You’ll notice when I say happiness, I mean peace. When a lot of people say happiness, they mean joy or bliss, but I’ll take peace.",
  "A happy person isn’t someone who’s happy all the time. It’s someone who effortlessly interprets events in such a way that they don’t lose their innate peace.",
  "Not to say you shouldn’t do things on the outside. You absolutely should. You’re a living creature. There are things you do. You locally reverse entropy. That’s why you’re here.",
  "Desire is a contract you make with yourself to be unhappy until you get what you want.",
  "When you’re young, you have time. You have health, but you have no money. When you’re middle-aged, you have money and you have health, but you have no time. When you’re old, you have money and you have time, but you have no health.",
  "By the time people realize they have enough money, they’ve lost their time and their health.",
  "Happiness is being satisfied with what you have. Success comes from dissatisfaction. Choose.",
  "In my case, there was definitely hedonic adaptation: I’d very quickly get used to anything.",
  "This led me to the conclusion, which seems trite, that happiness is internal. That conclusion set me on a path of working more on my internal self and realizing all real success is internal.",
  "The problem with getting good at a game, especially one with big rewards, is you continue playing it long after you should have outgrown it.",
  "The trick is knowing when to jump off and play instead.",
  "Those are the people who have such internal mental and self-control and self-awareness, they need nothing from anybody else.",
  "He’s at peace, he’s healthy, and whether he makes more money or less money compared to the next person has no effect on his mental state.",
  "You can get almost anything you want out of life, as long as it’s one thing and you want it far more than anything else.",
  "Peace is happiness at rest, and happiness is peace in motion.",
  "The only way to actually get peace on the inside is by giving up this idea of problems.",
  "Whenever the word “should” creeps up in your mind, it’s guilt or social programming.",
  "Doing something because you “should” basically means you don’t actually want to do it. It’s just making you miserable, so I’m trying to eliminate as many .",
  "The enemy of peace of mind is expectations drilled into you by society and other people.",
  "All the real scorecards are internal.",
  "One day, I realized with all these people I was jealous of, I couldn’t just choose little aspects of their life.",
  "It starts with realizing they’re skills you can learn. When you put your intention and focus on it, the world can become a better place.",
  "When working, surround yourself with people more successful than you. When playing, surround yourself with people happier than you.",
  "You decide it’s important to you. You prioritize it above everything else. You read everything on the topic. ",
  "Now I always look for the positive side of it. It used to take a rational effort. It used to take a few seconds for me to come up with a positive. Now I can do it sub-second. ",
  "I think working out every day made me happier. If you have peace of body, it’s easier to have peace of mind. ",
  "Hedonic adaptation is more powerful for man-made things (cars, houses, clothes, money) than for natural things (food, sex, exercise). ",
  "No exceptions—all screen activities linked to less happiness, all non-screen activities linked to more happiness. ",
  "A personal metric: how much of the day is spent doing things out of obligation rather than out of interest? ",
  "Increase serotonin in the brain without drugs: Sunlight, exercise, positive thinking, and tryptophan. ",
  "The phrase I probably use the most to myself in my head is just one word: “accept.” .",
  "It’s to be okay whatever the outcome is. It’s to be balanced and centered. It’s to step back and to see the grander scheme of things.",
  "We don’t always get what we want, but sometimes what is happening is for the best.",
  "Your life is a firefly blink in a night. You’re here for such a brief period of time.",
  "You’re going to die one day, and none of this is going to matter. So enjoy yourself. Do something positive. Project some love. Make someone happy. Laugh a little bit. Appreciate the moment. And do your work. ",
  "Mentors won’t make you rich.",
  "Ultimately, you have to take responsibility.",
  "All you should do is what you want to do. If you stop trying to figure out how to do things the way other people want you to do them, you get to listen to the little voice inside your head that wants to do things a certain way. Then, you get to be you.",
  "When everyone is sick, we no longer consider it a disease.",
  "“Easy choices, hard life. Hard choices, easy life.” .",
  "Value your time. It is all you have. It’s more important than your money. It’s more important than your friends. It is more important than anything. Your time is all you have. Do not waste your time.",
  "Anger is its own punishment. An angry person trying to push your head below water is drowning at the same time.",
  "A taste of freedom can make you unemployable.",
  "Even the group who colonizes Mars will disappear. No one is going to remember you past a certain number of generations, whether you’re an artist, a poet, a conqueror, a pauper, or anyone else. There’s no meaning.",
  "Understanding the long-term consequences of your actions. ",
  "There is actually nothing but this moment. No one has ever gone back in time, and no one has ever been able to successfully predict the future in any .",
  "Inspiration is perishable—act on it immediately.",
  "The democratization of technology allows anyone to be a creator, entrepreneur, scientist. The future is brighter.",
];


let quoteDisplay=document.getElementById('quoteDisplay')
let quoteButton=document.getElementById('quoteButton')


function randomQuote() {
    console.log('Function Ran')

    let randomNum=Math.floor(Math.random() *quotes.length)
    
    
    quoteDisplay.innerText=quotes[randomNum]
    
}

// quoteButton.addEventListener('click',randomQuote)